# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Continuous Integration
on:
  # Avoid triggering on pushes to /all/ open PR branches.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Bazel Test All (opt)
    runs-on: ubuntu-20.04
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel Cache
        uses: actions/cache@v1
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Install dependencies via apt
        run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
      # Note: xlscc is excluded because it builds Clang, and that pushes us
      # over 6 hours of build time.
      - name: Bazel Test All (opt)
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test -c opt -- //xls/... -//xls/contrib/xlscc/...
