name: Build And Deploy MkDocs

on:
# TODO(vmirian) 2022-02-02 Enable below to execute action on push.
#  push:
#    branches:
#    - main
#    paths:
#    - "**.md"
#    - "mkdocs.yml"
  workflow_dispatch:

jobs:
  docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
    - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Publish docs
      run: mkdocs gh-deploy
# TODO(vmirian) 2022-02-02 When action is live, enable message.
#      run: mkdocs gh-deploy -m "mkdocs generated documentation from ${GITHUB_SHA}"